server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;

  location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

 location /product {
  proxy_pass http://localhost:8080/product;
 }

 location /media {
  proxy_pass http://localhost:8080/media;
 }

 location /auth {
  proxy_pass http://localhost:8080/auth;
 }

 location /stores {
  proxy_pass http://localhost:8080/stores;
 }

location /branches {
  proxy_pass http://localhost:8080/branches;
 }

 location /orders {
  proxy_pass http://localhost:8080/orders;
 }
}
