import {CategoryIcon} from '../enums/category-icon.enum';

export const CATEGORY_ICON_MAP: Record<CategoryIcon, string> = {
  [CategoryIcon.WARNING_LIGHT]: 'icon-warning-light',
  [CategoryIcon.FORK_AND_SPOON]: 'icon-fork-and-spoon',
  [CategoryIcon.ALPACA]: 'icon-alpaca',
  [CategoryIcon.SIMPLE_PIG]: 'icon-simple-pig',
  [CategoryIcon.SCOOTER]: 'icon-scooter',
  [CategoryIcon.SCOOTER_3]: 'icon-scooter-3',
  [CategoryIcon.PIZZA]: 'icon-pizza',
  [CategoryIcon.PLUS_18]: 'icon-plus-18',
  [CategoryIcon.FAMILY_PLANNING_COMMISSION]: 'icon-family-planning-commission',
  [CategoryIcon.MAPPING_AND_GEOGRAPHY]: 'icon-mapping-and-geography',
  [CategoryIcon.ECONOMIC]: 'icon-economic',
  [CategoryIcon.EDUCATE]: 'icon-educate',
  [CategoryIcon.LEGISLATIVE]: 'icon-legislative',
  [CategoryIcon.DRUG]: 'icon-drug',
  [CategoryIcon.AIRPLANE]: 'icon-airplane',
  [CategoryIcon.HEADPHONES]: 'icon-headphones',
  [CategoryIcon.KIDSMODE]: 'icon-kidsmode',
  [CategoryIcon.CALL]: 'icon-call',
  [CategoryIcon.BUS]: 'icon-bus',
  [CategoryIcon.BASKETBALL]: 'icon-basketball',
  [CategoryIcon.GAMEPAD]: 'icon-gamepad',
  [CategoryIcon.GLASSES]: 'icon-glasses',
  [CategoryIcon.BOTTLE]: 'icon-bottle',
  [CategoryIcon.CAR_1]: 'icon-car-1',
  [CategoryIcon.COOK_CAP]: 'icon-cook-cap',
  [CategoryIcon.BED]: 'icon-bed',
  [CategoryIcon.BICYCLE]: 'icon-bicycle',
  [CategoryIcon.BAR]: 'icon-bar',
  [CategoryIcon.AMBULANCE]: 'icon-ambulance',
  [CategoryIcon.BIRTHDAY]: 'icon-birthday',
  [CategoryIcon.SHOP]: 'icon-shop',
  [CategoryIcon.ICE_CREAM]: 'icon-ice-cream',
  [CategoryIcon.HUMBURGER]: 'icon-humberger',
  [CategoryIcon.HONEY]: 'icon-honey',
  [CategoryIcon.DONUTS]: 'icon-donuts'
};
