INSERT INTO dbo.category (created_at, created_by, tenant_id, updated_at, updated_by, active, name, description, order_index)
VALUES
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Bebidas frías', 'Refrescos, jugos y agua fría', 1),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Bebidas calientes', 'Café, té y chocolate caliente', 2),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Panadería', 'Pan, bollería y productos horneados', 3),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Frutas', 'Frutas frescas de temporada', 4),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Verduras', 'Verduras y hortalizas frescas', 5),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Carnes', 'Carne de res, pollo y cerdo', 6),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Pescados y mariscos', 'Pescado fresco y mariscos', 7),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Lácteos', 'Leche, yogur y quesos', 8),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Huevos', 'Huevos de granja', 9),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Arroz y pastas', 'Arroz, fideos y pasta seca', 10),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Aceites y vinagres', 'Aceite de cocina y vinagres', 11),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Especias y condimentos', 'Sal, pimienta, hierbas y especias', 12),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Salsas', 'Salsas para cocinar y aderezos', 13),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Snacks', 'Galletas, papas fritas y frutos secos', 14),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Bebidas alcohólicas', 'Cerveza, vino y licores', 15),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Cereales', 'Cereales para desayuno y avena', 16),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Pan de molde', 'Pan en rebanadas y tostadas', 17),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Productos congelados', 'Verduras, carnes y comidas preparadas', 18),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Helados', 'Helados y postres congelados', 19),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Jugos naturales', 'Jugos exprimidos y batidos', 20),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Pan integral', 'Pan saludable y integral', 21),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Dulces', 'Caramelos, chocolates y golosinas', 22),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Galletas', 'Galletas dulces y saladas', 23),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Harinas', 'Harina de trigo, maíz y mezclas', 24),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Legumbres', 'Frijoles, lentejas y garbanzos', 25),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Quesos', 'Quesos frescos y madurados', 26),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Yogur', 'Yogur natural y de sabores', 27),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Café', 'Café molido y en grano', 28),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Té', 'Tés y tisanas', 29),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Chocolate', 'Cacao y chocolates', 30),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Bebidas energéticas', 'Bebidas y suplementos energéticos', 31),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Pan de hamburguesa', 'Pan para hamburguesas y hot dogs', 32),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Pan artesanal', 'Pan artesanal y gourmet', 33),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Postres', 'Tartas, pasteles y postres variados', 34),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Snacks saludables', 'Frutos secos y barras energéticas', 35),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Cerveza', 'Cervezas nacionales e importadas', 36),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Vino', 'Vinos tintos, blancos y rosados', 37),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Licores', 'Licores y destilados', 38),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Bebidas sin alcohol', 'Refrescos y aguas saborizadas', 39),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Aceitunas y encurtidos', 'Aceitunas, pepinillos y encurtidos', 40),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Sopas y cremas', 'Sopas listas para calentar', 41),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Mermeladas y miel', 'Mermeladas, jaleas y miel', 42),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Snacks para niños', 'Galletas y golosinas para niños', 43),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Bebidas calientes especiales', 'Cafés gourmet y tés especiales', 44),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Comidas rápidas', 'Hamburguesas, pizzas y hot dogs', 45),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Ensaladas', 'Ensaladas frescas y preparadas', 46),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Sushi', 'Sushi fresco y combos', 47),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Bebidas lácteas', 'Leches saborizadas y batidos', 48),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Panadería dulce', 'Bizcochos y muffins', 49),
(NOW(), 'system', 'tenant_1', NOW(), 'system', true, 'Panadería salada', 'Pan de ajo, pan relleno y focaccias', 50);


INSERT INTO dbo.product (id, category_id, tenant_id, name, description, technical_details, brand, min_stock, status, created_at, updated_at)
VALUES
(1, 1, 'tenant_1', 'Laptop Lenovo ThinkPad E14', 'Laptop de 14 pulgadas ideal para oficina', 'Intel i5, 16GB RAM, 512GB SSD', 'Lenovo', 5, 'ACTIVE', NOW(), NOW()),
(2, 1, 'tenant_1', 'Laptop HP Pavilion 15', 'Laptop versátil con diseño moderno', 'AMD Ryzen 5, 8GB RAM, 512GB SSD', 'HP', 5, 'ACTIVE', NOW(), NOW()),
(3, 2, 'tenant_2', 'Smartphone Samsung Galaxy A54', 'Teléfono inteligente de gama media', '128GB almacenamiento, Android 14', 'Samsung', 10, 'ACTIVE', NOW(), NOW()),
(4, 2, 'tenant_2', 'Smartphone Xiaomi Redmi Note 13', 'Gran rendimiento a bajo costo', 'Snapdragon 7s Gen 2, 6GB RAM', 'Xiaomi', 10, 'ACTIVE', NOW(), NOW()),
(5, 3, 'tenant_3', 'Smart TV LG OLED 55"', 'Televisor OLED con IA y HDR10', '55 pulgadas, 4K UHD, WebOS', 'LG', 3, 'ACTIVE', NOW(), NOW()),
(6, 3, 'tenant_3', 'Smart TV Samsung QLED 65"', 'Televisor QLED de gran formato', '65 pulgadas, 4K UHD, Tizen OS', 'Samsung', 3, 'ACTIVE', NOW(), NOW()),
(7, 4, 'tenant_4', 'Bicicleta MTB Rod 29"', 'Bicicleta de montaña para adultos', '29 pulgadas, 21 velocidades', 'Trek', 2, 'ACTIVE', NOW(), NOW()),
(8, 4, 'tenant_4', 'Bicicleta de Ruta Carbono', 'Bicicleta ligera para carretera', 'Carbono, 22 velocidades', 'Giant', 2, 'ACTIVE', NOW(), NOW()),
(9, 5, 'tenant_5', 'Tenis Nike Air Max', 'Tenis deportivos cómodos y resistentes', 'Talla 42, color blanco', 'Nike', 10, 'ACTIVE', NOW(), NOW()),
(10, 5, 'tenant_5', 'Tenis Adidas Ultraboost', 'Running para alto rendimiento', 'Talla 43, color negro', 'Adidas', 10, 'ACTIVE', NOW(), NOW()),
(11, 6, 'tenant_6', 'Aceite de Oliva Extra Virgen 1L', 'Aceite de oliva prensado en frío', 'Origen: España, botella de vidrio', 'Carbonell', 20, 'ACTIVE', NOW(), NOW()),
(12, 6, 'tenant_6', 'Café Molido Premium 500g', 'Café arábica de alta calidad', 'Origen: Colombia, tostado medio', 'Juan Valdez', 30, 'ACTIVE', NOW(), NOW()),
(13, 7, 'tenant_7', 'Perfume Chanel Nº5 50ml', 'Perfume clásico femenino', 'Notas florales, 50ml', 'Chanel', 15, 'ACTIVE', NOW(), NOW()),
(14, 7, 'tenant_7', 'Loción Corporal Nivea 200ml', 'Hidratante para todo tipo de piel', '200ml, aroma suave', 'Nivea', 25, 'ACTIVE', NOW(), NOW()),
(15, 8, 'tenant_8', 'Neumático Goodyear 205/55R16', 'Neumático para automóvil', '205/55R16, alta durabilidad', 'Goodyear', 50, 'ACTIVE', NOW(), NOW()),
(16, 8, 'tenant_8', 'Aceite Motor Castrol 5W30 4L', 'Aceite lubricante sintético', '4 litros, motor gasolina', 'Castrol', 40, 'ACTIVE', NOW(), NOW()),
(17, 9, 'tenant_9', 'Libro "Cien Años de Soledad"', 'Novela clásica de Gabriel García Márquez', 'Editorial: Sudamericana', 'Gabriel García Márquez', 20, 'ACTIVE', NOW(), NOW()),
(18, 9, 'tenant_9', 'Libro "El Principito"', 'Fábula filosófica para todas las edades', 'Editorial: Salamandra', 'Antoine de Saint-Exupéry', 20, 'ACTIVE', NOW(), NOW()),
(19, 10, 'tenant_10', 'Guitarra Acústica Yamaha F310', 'Guitarra acústica de cuerdas de nylon', 'Madera maciza, color natural', 'Yamaha', 5, 'ACTIVE', NOW(), NOW()),
(20, 10, 'tenant_10', 'Teclado Electrónico Casio CT-X700', 'Teclado con 61 teclas y múltiples tonos', '61 teclas, 600 sonidos', 'Casio', 5, 'ACTIVE', NOW(), NOW()),
(21, 1, 'tenant_1', 'Auriculares Sony WH-1000XM5', 'Auriculares inalámbricos con cancelación de ruido', 'Bluetooth, 30 horas de batería', 'Sony', 10, 'ACTIVE', NOW(), NOW()),
(22, 1, 'tenant_1', 'Monitor LG 27" UltraWide', 'Monitor ultrapanorámico para productividad', '27 pulgadas, resolución 2560x1080', 'LG', 5, 'ACTIVE', NOW(), NOW()),
(23, 2, 'tenant_2', 'Camisa Polo Ralph Lauren', 'Camisa casual de algodón', 'Color azul, talla M', 'Ralph Lauren', 10, 'ACTIVE', NOW(), NOW()),
(24, 2, 'tenant_2', 'Chaqueta North Face', 'Chaqueta impermeable y térmica', 'Color negro, talla L', 'The North Face', 5, 'ACTIVE', NOW(), NOW()),
(25, 3, 'tenant_3', 'Refrigerador Samsung 350L', 'Refrigerador con congelador superior', 'Capacidad 350L, eficiencia A++', 'Samsung', 3, 'ACTIVE', NOW(), NOW()),
(26, 3, 'tenant_3', 'Horno Microondas LG 28L', 'Microondas digital con grill', '28 litros, 900W', 'LG', 5, 'ACTIVE', NOW(), NOW()),
(27, 4, 'tenant_4', 'Balón de Fútbol Adidas', 'Balón oficial de tamaño 5', 'Material sintético, cosido a mano', 'Adidas', 20, 'ACTIVE', NOW(), NOW()),
(28, 4, 'tenant_4', 'Raqueta Tenis Wilson Pro Staff', 'Raqueta profesional de tenis', 'Peso 310g, grip 4 3/8', 'Wilson', 5, 'ACTIVE', NOW(), NOW()),
(29, 5, 'tenant_5', 'Zapatillas Converse All Star', 'Zapatillas clásicas de lona', 'Talla 42, color blanco', 'Converse', 15, 'ACTIVE', NOW(), NOW()),
(30, 5, 'tenant_5', 'Sandalias Birkenstock Arizona', 'Sandalias cómodas y duraderas', 'Color marrón, talla 40', 'Birkenstock', 10, 'ACTIVE', NOW(), NOW()),
(31, 6, 'tenant_6', 'Leche Entera Lala 1L', 'Leche pasteurizada entera', '1 litro, envase carton', 'Lala', 50, 'ACTIVE', NOW(), NOW()),
(32, 6, 'tenant_6', 'Yogur Griego Danone 500g', 'Yogur natural griego', '500 gramos, sabor natural', 'Danone', 30, 'ACTIVE', NOW(), NOW()),
(33, 7, 'tenant_7', 'Champú Head & Shoulders 400ml', 'Champú anticaspa', '400ml, aroma menta', 'H&S', 25, 'ACTIVE', NOW(), NOW()),
(34, 7, 'tenant_7', 'Crema Nivea Q10 200ml', 'Crema facial reafirmante', '200ml, crema hidratante', 'Nivea', 15, 'ACTIVE', NOW(), NOW()),
(35, 8, 'tenant_8', 'Batería Exide 12V 60Ah', 'Batería de automóvil', '12V, 60Ah, mantenimiento libre', 'Exide', 20, 'ACTIVE', NOW(), NOW()),
(36, 8, 'tenant_8', 'Filtro de Aceite Bosch', 'Filtro para motor de automóvil', 'Medida universal', 'Bosch', 50, 'ACTIVE', NOW(), NOW()),
(37, 9, 'tenant_9', 'Libro "Don Quijote"', 'Novela clásica española', 'Editorial: Espasa', 'Miguel de Cervantes', 10, 'ACTIVE', NOW(), NOW()),
(38, 9, 'tenant_9', 'Libro "1984"', 'Novela distópica de George Orwell', 'Editorial: Secker & Warburg', 'George Orwell', 10, 'ACTIVE', NOW(), NOW()),
(39, 10, 'tenant_10', 'Bajo Eléctrico Fender', 'Bajo de 4 cuerdas', 'Color sunburst, maple neck', 'Fender', 5, 'ACTIVE', NOW(), NOW()),
(40, 10, 'tenant_10', 'Batería Electrónica Roland', 'Kit completo de batería electrónica', '13 pads, módulo TD-17', 'Roland', 2, 'ACTIVE', NOW(), NOW()),
(41, 1, 'tenant_1', 'Router WiFi TP-Link', 'Router inalámbrico de doble banda', 'AC1200, 4 puertos LAN', 'TP-Link', 10, 'ACTIVE', NOW(), NOW()),
(42, 1, 'tenant_1', 'Disco SSD Kingston 1TB', 'Disco sólido de alta velocidad', 'SATA III, 1TB', 'Kingston', 5, 'ACTIVE', NOW(), NOW()),
(43, 2, 'tenant_2', 'Pantalón Jeans Levi’s', 'Jeans clásico de mezclilla', 'Talla 32, color azul', 'Levi’s', 15, 'ACTIVE', NOW(), NOW()),
(44, 2, 'tenant_2', 'Abrigo Patagonia', 'Abrigo térmico para invierno', 'Color negro, talla L', 'Patagonia', 5, 'ACTIVE', NOW(), NOW()),
(45, 3, 'tenant_3', 'Lavadora LG 7kg', 'Lavadora de carga frontal', '7 kg, eficiencia A++', 'LG', 5, 'ACTIVE', NOW(), NOW()),
(46, 3, 'tenant_3', 'Secadora Samsung 8kg', 'Secadora de ropa', '8 kg, sensor de humedad', 'Samsung', 5, 'ACTIVE', NOW(), NOW()),
(47, 4, 'tenant_4', 'Guantes de Boxeo Everlast', 'Guantes profesionales', 'Peso 12oz, color rojo', 'Everlast', 10, 'ACTIVE', NOW(), NOW()),
(48, 4, 'tenant_4', 'Casco de Ciclismo Giro', 'Casco de seguridad', 'Talla M, color negro', 'Giro', 10, 'ACTIVE', NOW(), NOW()),
(49, 5, 'tenant_5', 'Calcetines Deportivos Puma', 'Calcetines transpirables', 'Pack de 3 pares', 'Puma', 50, 'ACTIVE', NOW(), NOW()),
(50, 5, 'tenant_5', 'Camiseta Adidas Originals', 'Camiseta casual', 'Talla M, color blanco', 'Adidas', 20, 'ACTIVE', NOW(), NOW());

INSERT INTO dbo.product (id, category_id, tenant_id, name, description, technical_details, brand, min_stock, status, created_at, updated_at)
VALUES
(51, 6, 'tenant_6', 'Arroz Integral 1kg', 'Arroz integral de alta calidad', 'Paquete de 1 kg', 'La Fina', 50, 'ACTIVE', NOW(), NOW()),
(52, 6, 'tenant_6', 'Harina de Trigo 1kg', 'Harina para repostería y cocina', 'Paquete de 1 kg', 'Molinos Modernos', 50, 'ACTIVE', NOW(), NOW()),
(53, 7, 'tenant_7', 'Jabón Dove 100g', 'Jabón suave para piel sensible', 'Paquete de 3 unidades', 'Dove', 30, 'ACTIVE', NOW(), NOW()),
(54, 7, 'tenant_7', 'Crema Nivea Soft 150ml', 'Hidratante para rostro y manos', '150ml, textura ligera', 'Nivea', 25, 'ACTIVE', NOW(), NOW()),
(55, 8, 'tenant_8', 'Correa de Seguridad Auto', 'Correa para cinturón de seguridad', 'Color negro, regulable', 'Bosch', 50, 'ACTIVE', NOW(), NOW()),
(56, 8, 'tenant_8', 'Pastillas de Freno Brembo', 'Pastillas para frenos delanteros', 'Modelo universal', 'Brembo', 30, 'ACTIVE', NOW(), NOW()),
(57, 9, 'tenant_9', 'Libro "La Sombra del Viento"', 'Novela de suspense literario', 'Editorial: Planeta', 'Carlos Ruiz Zafón', 15, 'ACTIVE', NOW(), NOW()),
(58, 9, 'tenant_9', 'Libro "El Alquimista"', 'Novela motivacional y filosófica', 'Editorial: HarperCollins', 'Paulo Coelho', 20, 'ACTIVE', NOW(), NOW()),
(59, 10, 'tenant_10', 'Teclado MIDI Akai MPK Mini', 'Teclado compacto para producción musical', '25 teclas, 8 pads, 2 knobs', 'Akai', 5, 'ACTIVE', NOW(), NOW()),
(60, 10, 'tenant_10', 'Micrófono Condensador Audio-Technica', 'Micrófono profesional para estudio', 'Patrón cardioide, 48V phantom', 'Audio-Technica', 5, 'ACTIVE', NOW(), NOW()),
(61, 1, 'tenant_1', 'Tablet Samsung Galaxy Tab S8', 'Tablet para productividad y entretenimiento', '11 pulgadas, 128GB almacenamiento', 'Samsung', 10, 'ACTIVE', NOW(), NOW()),
(62, 1, 'tenant_1', 'Tablet Apple iPad 10th Gen', 'Tablet con iOS y Apple Pencil', '10.9 pulgadas, 64GB', 'Apple', 5, 'ACTIVE', NOW(), NOW()),
(63, 2, 'tenant_2', 'Camiseta Under Armour', 'Camiseta deportiva transpirable', 'Talla M, color gris', 'Under Armour', 20, 'ACTIVE', NOW(), NOW()),
(64, 2, 'tenant_2', 'Pantalón Deportivo Nike', 'Pantalón cómodo para entrenamiento', 'Talla L, color negro', 'Nike', 15, 'ACTIVE', NOW(), NOW()),
(65, 3, 'tenant_3', 'Aspiradora Dyson V11', 'Aspiradora inalámbrica potente', 'Potencia 185AW, batería 60 min', 'Dyson', 5, 'ACTIVE', NOW(), NOW()),
(66, 3, 'tenant_3', 'Robot Aspirador Roomba i7+', 'Aspiradora robot con mapeo inteligente', 'Compatible con app, carga automática', 'iRobot', 5, 'ACTIVE', NOW(), NOW()),
(67, 4, 'tenant_4', 'Pelota Baloncesto Spalding', 'Balón oficial para entrenamiento y juego', 'Tamaño 7, material sintético', 'Spalding', 20, 'ACTIVE', NOW(), NOW()),
(68, 4, 'tenant_4', 'Raqueta Pádel Head', 'Raqueta profesional de pádel', 'Peso 360g, grip 2', 'Head', 5, 'ACTIVE', NOW(), NOW()),
(69, 5, 'tenant_5', 'Zapatillas New Balance 574', 'Zapatillas casuales deportivas', 'Talla 42, color gris', 'New Balance', 15, 'ACTIVE', NOW(), NOW()),
(70, 5, 'tenant_5', 'Botas Timberland Classic', 'Botas resistentes para exterior', 'Talla 43, color marrón', 'Timberland', 10, 'ACTIVE', NOW(), NOW()),
(71, 6, 'tenant_6', 'Aceite de Girasol 1L', 'Aceite vegetal puro', 'Paquete 1 litro', 'Cocinero', 30, 'ACTIVE', NOW(), NOW()),
(72, 6, 'tenant_6', 'Miel Natural 500g', 'Miel pura de abeja', 'Envase de 500g', 'Apícola Real', 20, 'ACTIVE', NOW(), NOW()),
(73, 7, 'tenant_7', 'Desodorante Rexona 150ml', 'Desodorante en spray', '150ml, aroma fresco', 'Rexona', 25, 'ACTIVE', NOW(), NOW()),
(74, 7, 'tenant_7', 'Crema Facial L’Oréal Hydra', 'Crema hidratante facial', '50ml, textura ligera', 'L’Oréal', 20, 'ACTIVE', NOW(), NOW()),
(75, 8, 'tenant_8', 'Bujía NGK', 'Bujía para motor', 'Compatible con varios motores', 'NGK', 50, 'ACTIVE', NOW(), NOW()),
(76, 8, 'tenant_8', 'Amortiguador Monroe', 'Amortiguador de suspensión', 'Modelo universal', 'Monroe', 30, 'ACTIVE', NOW(), NOW()),
(77, 9, 'tenant_9', 'Libro "Sapiens"', 'Historia de la humanidad', 'Editorial: Debate', 'Yuval Noah Harari', 15, 'ACTIVE', NOW(), NOW()),
(78, 9, 'tenant_9', 'Libro "Homo Deus"', 'Futuro de la humanidad', 'Editorial: Debate', 'Yuval Noah Harari', 15, 'ACTIVE', NOW(), NOW()),
(79, 10, 'tenant_10', 'Guitarra Eléctrica Ibanez RG', 'Guitarra eléctrica profesional', 'Color negro, 24 trastes', 'Ibanez', 5, 'ACTIVE', NOW(), NOW()),
(80, 10, 'tenant_10', 'Teclado MIDI Novation Launchkey', 'Teclado para producción musical', '25 teclas, 8 pads', 'Novation', 5, 'ACTIVE', NOW(), NOW()),
(81, 1, 'tenant_1', 'Auriculares Bose QuietComfort 45', 'Auriculares inalámbricos premium', 'Cancelación de ruido activa', 'Bose', 10, 'ACTIVE', NOW(), NOW()),
(82, 1, 'tenant_1', 'Monitor Dell UltraSharp 27"', 'Monitor profesional para diseño', '27 pulgadas, resolución 4K', 'Dell', 5, 'ACTIVE', NOW(), NOW()),
(83, 2, 'tenant_2', 'Camisa Levi’s Manga Larga', 'Camisa casual de mezclilla', 'Talla M, color azul', 'Levi’s', 15, 'ACTIVE', NOW(), NOW()),
(84, 2, 'tenant_2', 'Chaqueta Columbia', 'Chaqueta impermeable y térmica', 'Talla L, color gris', 'Columbia', 5, 'ACTIVE', NOW(), NOW()),
(85, 3, 'tenant_3', 'Refrigerador Whirlpool 300L', 'Refrigerador con congelador superior', '300L, eficiencia energética A+', 'Whirlpool', 3, 'ACTIVE', NOW(), NOW()),
(86, 3, 'tenant_3', 'Horno Microondas Panasonic 25L', 'Microondas digital con grill', '25 litros, 800W', 'Panasonic', 5, 'ACTIVE', NOW(), NOW()),
(87, 4, 'tenant_4', 'Balón Voleibol Mikasa', 'Balón oficial de voleibol', 'Tamaño 5, material sintético', 'Mikasa', 20, 'ACTIVE', NOW(), NOW()),
(88, 4, 'tenant_4', 'Raqueta Squash Dunlop', 'Raqueta profesional de squash', 'Peso 150g', 'Dunlop', 5, 'ACTIVE', NOW(), NOW()),
(89, 5, 'tenant_5', 'Zapatillas Reebok Classic', 'Zapatillas clásicas retro', 'Talla 42, color blanco', 'Reebok', 15, 'ACTIVE', NOW(), NOW()),
(90, 5, 'tenant_5', 'Sandalias Crocs', 'Sandalias cómodas y ligeras', 'Talla 40, color azul', 'Crocs', 20, 'ACTIVE', NOW(), NOW()),
(91, 6, 'tenant_6', 'Leche Deslactosada 1L', 'Leche sin lactosa', '1 litro, envase carton', 'Lala', 50, 'ACTIVE', NOW(), NOW()),
(92, 6, 'tenant_6', 'Yogur Natural 1kg', 'Yogur natural fresco', '1 kg, sabor natural', 'Danone', 30, 'ACTIVE', NOW(), NOW()),
(93, 7, 'tenant_7', 'Champú Pantene 400ml', 'Champú nutritivo', '400ml, aroma floral', 'Pantene', 25, 'ACTIVE', NOW(), NOW()),
(94, 7, 'tenant_7', 'Crema Facial Garnier 50ml', 'Hidratante ligera para rostro', '50ml, textura ligera', 'Garnier', 20, 'ACTIVE', NOW(), NOW()),
(95, 8, 'tenant_8', 'Batería Varta 12V 55Ah', 'Batería de automóvil', '12V, 55Ah, libre de mantenimiento', 'Varta', 20, 'ACTIVE', NOW(), NOW()),
(96, 8, 'tenant_8', 'Filtro de Aire K&N', 'Filtro de alto flujo para motor', 'Modelo universal', 'K&N', 50, 'ACTIVE', NOW(), NOW()),
(97, 9, 'tenant_9', 'Libro "El Código Da Vinci"', 'Novela de misterio y suspenso', 'Editorial: Planeta', 'Dan Brown', 15, 'ACTIVE', NOW(), NOW()),
(98, 9, 'tenant_9', 'Libro "Angeles y Demonios"', 'Novela de misterio y conspiración', 'Editorial: Planeta', 'Dan Brown', 15, 'ACTIVE', NOW(), NOW()),
(99, 10, 'tenant_10', 'Bajo Eléctrico Ibanez GSR', 'Bajo de 4 cuerdas profesional', 'Color negro, maple neck', 'Ibanez', 5, 'ACTIVE', NOW(), NOW()),
(100, 10, 'tenant_10', 'Batería Acústica Pearl', 'Kit de batería acústica completo', '5 tambores, 3 platillos', 'Pearl', 2, 'ACTIVE', NOW(), NOW());


INSERT INTO dbo.product (id, category_id, tenant_id, name, description, technical_details, brand, min_stock, status, created_at, updated_at)
VALUES
(101, 1, 'tenant_1', 'Laptop Dell Inspiron 15', 'Laptop de 15 pulgadas para uso diario', 'Intel i5, 8GB RAM, 256GB SSD', 'Dell', 5, 'ACTIVE', NOW(), NOW()),
(102, 1, 'tenant_1', 'Laptop ASUS ZenBook 14', 'Laptop ligera y potente', 'Intel i7, 16GB RAM, 512GB SSD', 'ASUS', 5, 'ACTIVE', NOW(), NOW()),
(103, 2, 'tenant_2', 'Smartphone OnePlus Nord 3', 'Teléfono inteligente con buena cámara', '128GB almacenamiento, 12GB RAM', 'OnePlus', 10, 'ACTIVE', NOW(), NOW()),
(104, 2, 'tenant_2', 'Smartphone Realme GT 2', 'Teléfono económico con gran rendimiento', '256GB almacenamiento, 8GB RAM', 'Realme', 10, 'ACTIVE', NOW(), NOW()),
(105, 3, 'tenant_3', 'Smart TV Sony Bravia 55"', 'Televisor con calidad de imagen superior', '55 pulgadas, 4K UHD, Android TV', 'Sony', 3, 'ACTIVE', NOW(), NOW()),
(106, 3, 'tenant_3', 'Smart TV Hisense 50"', 'Televisor inteligente con buena relación calidad-precio', '50 pulgadas, 4K UHD, VIDAA OS', 'Hisense', 3, 'ACTIVE', NOW(), NOW()),
(107, 4, 'tenant_4', 'Bicicleta MTB Scott 29"', 'Bicicleta de montaña profesional', '29 pulgadas, 24 velocidades', 'Scott', 2, 'ACTIVE', NOW(), NOW()),
(108, 4, 'tenant_4', 'Bicicleta Ruta Specialized', 'Bicicleta ligera para carretera', 'Carbono, 22 velocidades', 'Specialized', 2, 'ACTIVE', NOW(), NOW()),
(109, 5, 'tenant_5', 'Tenis Puma RS-X', 'Tenis deportivos para entrenamiento', 'Talla 42, color rojo', 'Puma', 10, 'ACTIVE', NOW(), NOW()),
(110, 5, 'tenant_5', 'Tenis New Balance 860', 'Running de alto rendimiento', 'Talla 43, color negro', 'New Balance', 10, 'ACTIVE', NOW(), NOW()),
(111, 6, 'tenant_6', 'Aceite de Oliva 500ml', 'Aceite de oliva puro', 'Botella 500ml', 'Carbonell', 20, 'ACTIVE', NOW(), NOW()),
(112, 6, 'tenant_6', 'Café en Grano Lavazza 1kg', 'Café premium en grano', '1kg, tueste medio', 'Lavazza', 30, 'ACTIVE', NOW(), NOW()),
(113, 7, 'tenant_7', 'Perfume Dior Sauvage 100ml', 'Perfume masculino', '100ml, notas amaderadas', 'Dior', 15, 'ACTIVE', NOW(), NOW()),
(114, 7, 'tenant_7', 'Loción Corporal Vaseline 200ml', 'Hidratante para piel seca', '200ml, aroma neutro', 'Vaseline', 25, 'ACTIVE', NOW(), NOW()),
(115, 8, 'tenant_8', 'Neumático Pirelli 205/55R16', 'Neumático para automóvil', '205/55R16, alta durabilidad', 'Pirelli', 50, 'ACTIVE', NOW(), NOW()),
(116, 8, 'tenant_8', 'Aceite Motor Shell Helix 5W40 4L', 'Aceite sintético para motor', '4 litros, motor gasolina', 'Shell', 40, 'ACTIVE', NOW(), NOW()),
(117, 9, 'tenant_9', 'Libro "El Hobbit"', 'Novela fantástica de J.R.R. Tolkien', 'Editorial: Minotauro', 'J.R.R. Tolkien', 20, 'ACTIVE', NOW(), NOW()),
(118, 9, 'tenant_9', 'Libro "Matar a un Ruiseñor"', 'Novela clásica estadounidense', 'Editorial: Lumen', 'Harper Lee', 20, 'ACTIVE', NOW(), NOW()),
(119, 10, 'tenant_10', 'Guitarra Acústica Fender CD-60', 'Guitarra acústica de iniciación', 'Cuerdas de acero, color natural', 'Fender', 5, 'ACTIVE', NOW(), NOW()),
(120, 10, 'tenant_10', 'Teclado Casio LK-S250', 'Teclado portátil con luces guía', '61 teclas, 400 sonidos', 'Casio', 5, 'ACTIVE', NOW(), NOW()),
(121, 1, 'tenant_1', 'Auriculares JBL Tune 750', 'Auriculares inalámbricos con cancelación de ruido', 'Bluetooth, 15 horas batería', 'JBL', 10, 'ACTIVE', NOW(), NOW()),
(122, 1, 'tenant_1', 'Monitor Samsung 27" Curvo', 'Monitor curvo para productividad', '27 pulgadas, resolución 2560x1080', 'Samsung', 5, 'ACTIVE', NOW(), NOW()),
(123, 2, 'tenant_2', 'Camisa Tommy Hilfiger', 'Camisa casual elegante', 'Talla M, color azul', 'Tommy Hilfiger', 10, 'ACTIVE', NOW(), NOW()),
(124, 2, 'tenant_2', 'Chaqueta Jack & Jones', 'Chaqueta casual resistente', 'Talla L, color gris', 'Jack & Jones', 5, 'ACTIVE', NOW(), NOW()),
(125, 3, 'tenant_3', 'Refrigerador Bosch 300L', 'Refrigerador con congelador superior', '300L, eficiencia A+', 'Bosch', 3, 'ACTIVE', NOW(), NOW()),
(126, 3, 'tenant_3', 'Horno Microondas Samsung 28L', 'Microondas digital con grill', '28L, 900W', 'Samsung', 5, 'ACTIVE', NOW(), NOW()),
(127, 4, 'tenant_4', 'Balón Fútbol Mitre', 'Balón oficial tamaño 5', 'Material sintético, cosido a mano', 'Mitre', 20, 'ACTIVE', NOW(), NOW()),
(128, 4, 'tenant_4', 'Raqueta Tenis Babolat Pure Drive', 'Raqueta profesional', 'Peso 300g, grip 4 1/4', 'Babolat', 5, 'ACTIVE', NOW(), NOW()),
(129, 5, 'tenant_5', 'Zapatillas Vans Old Skool', 'Zapatillas casuales clásicas', 'Talla 42, color negro', 'Vans', 15, 'ACTIVE', NOW(), NOW()),
(130, 5, 'tenant_5', 'Sandalias Teva Original', 'Sandalias cómodas para trekking', 'Talla 40, color marrón', 'Teva', 10, 'ACTIVE', NOW(), NOW()),
(131, 6, 'tenant_6', 'Leche Semidescremada 1L', 'Leche pasteurizada semidescremada', '1 litro, envase carton', 'Lala', 50, 'ACTIVE', NOW(), NOW()),
(132, 6, 'tenant_6', 'Yogur Natural Danone 1kg', 'Yogur fresco natural', '1 kg, sabor natural', 'Danone', 30, 'ACTIVE', NOW(), NOW()),
(133, 7, 'tenant_7', 'Champú Herbal Essences 400ml', 'Champú nutritivo', '400ml, aroma floral', 'Herbal Essences', 25, 'ACTIVE', NOW(), NOW()),
(134, 7, 'tenant_7', 'Crema Facial L’Oréal Men Expert', 'Hidratante ligera para rostro', '50ml, textura ligera', 'L’Oréal', 20, 'ACTIVE', NOW(), NOW()),
(135, 8, 'tenant_8', 'Batería Yuasa 12V 55Ah', 'Batería de automóvil', '12V, 55Ah, libre de mantenimiento', 'Yuasa', 20, 'ACTIVE', NOW(), NOW()),
(136, 8, 'tenant_8', 'Filtro Aire Mann', 'Filtro de alto flujo para motor', 'Modelo universal', 'Mann', 50, 'ACTIVE', NOW(), NOW()),
(137, 9, 'tenant_9', 'Libro "Crimen y Castigo"', 'Novela clásica rusa', 'Editorial: Alianza', 'Fiódor Dostoyevski', 15, 'ACTIVE', NOW(), NOW()),
(138, 9, 'tenant_9', 'Libro "La Casa de los Espíritus"', 'Novela latinoamericana', 'Editorial: Plaza & Janés', 'Isabel Allende', 15, 'ACTIVE', NOW(), NOW()),
(139, 10, 'tenant_10', 'Bajo Eléctrico Cort', 'Bajo profesional de 4 cuerdas', 'Color negro, maple neck', 'Cort', 5, 'ACTIVE', NOW(), NOW()),
(140, 10, 'tenant_10', 'Batería Electrónica Alesis', 'Kit de batería electrónica completo', '12 pads, módulo Surge', 'Alesis', 2, 'ACTIVE', NOW(), NOW()),
(141, 1, 'tenant_1', 'Router WiFi Asus AC1200', 'Router inalámbrico de doble banda', 'Velocidad 1200 Mbps', 'Asus', 15, 'ACTIVE', NOW(), NOW()),
(142, 1, 'tenant_1', 'Switch Netgear 8 Puertos', 'Switch para red doméstica', '8 puertos Gigabit', 'Netgear', 10, 'ACTIVE', NOW(), NOW()),
(143, 2, 'tenant_2', 'Auriculares Sony WH-1000XM4', 'Auriculares inalámbricos premium', 'Cancelación activa de ruido', 'Sony', 10, 'ACTIVE', NOW(), NOW()),
(144, 2, 'tenant_2', 'Altavoz Bluetooth JBL Flip 6', 'Altavoz portátil con gran sonido', '20W, resistente al agua', 'JBL', 15, 'ACTIVE', NOW(), NOW()),
(145, 3, 'tenant_3', 'Microondas LG 30L', 'Microondas digital con grill', '30L, 1000W', 'LG', 5, 'ACTIVE', NOW(), NOW()),
(146, 3, 'tenant_3', 'Lavadora Samsung 8kg', 'Lavadora automática', '8kg, 1200 rpm', 'Samsung', 3, 'ACTIVE', NOW(), NOW()),
(147, 4, 'tenant_4', 'Pelota Baloncesto Wilson', 'Balón oficial NBA', 'Tamaño 7, material sintético', 'Wilson', 20, 'ACTIVE', NOW(), NOW()),
(148, 4, 'tenant_4', 'Raqueta Pádel Bullpadel', 'Raqueta profesional', 'Peso 360g, grip 2', 'Bullpadel', 5, 'ACTIVE', NOW(), NOW()),
(149, 5, 'tenant_5', 'Zapatillas Adidas Superstar', 'Zapatillas clásicas', 'Talla 42, color blanco', 'Adidas', 15, 'ACTIVE', NOW(), NOW()),
(150, 5, 'tenant_5', 'Botas Caterpillar', 'Botas resistentes', 'Talla 43, color marrón', 'Caterpillar', 10, 'ACTIVE', NOW(), NOW());

-- =====================================
-- PRODUCTOS 151-200
-- =====================================
INSERT INTO dbo.product (id, category_id, tenant_id, name, description, technical_details, brand, min_stock, status, created_at, updated_at)
VALUES
(151, 6, 'tenant_6', 'Pan Integral 500g', 'Pan integral saludable', 'Paquete de 500g', 'Bimbo', 50, 'ACTIVE', NOW(), NOW()),
(152, 6, 'tenant_6', 'Galletas María 250g', 'Galletas dulces clásicas', 'Paquete de 250g', 'María', 50, 'ACTIVE', NOW(), NOW()),
(153, 7, 'tenant_7', 'Gel Dentífrico Colgate 100ml', 'Pasta dental con fluor', '100ml, sabor menta', 'Colgate', 30, 'ACTIVE', NOW(), NOW()),
(154, 7, 'tenant_7', 'Enjuague Bucal Listerine 500ml', 'Enjuague antibacteriano', '500ml, sabor mentol', 'Listerine', 25, 'ACTIVE', NOW(), NOW()),
(155, 8, 'tenant_8', 'Pastillas de Freno Bosch', 'Pastillas para freno delantero', 'Modelo universal', 'Bosch', 50, 'ACTIVE', NOW(), NOW()),
(156, 8, 'tenant_8', 'Aceite de Motor Castrol 5W30', 'Aceite sintético para motor', '4 litros, motor gasolina', 'Castrol', 40, 'ACTIVE', NOW(), NOW()),
(157, 9, 'tenant_9', 'Libro "1984"', 'Novela distópica clásica', 'Editorial: Debolsillo', 'George Orwell', 20, 'ACTIVE', NOW(), NOW()),
(158, 9, 'tenant_9', 'Libro "Rebelión en la Granja"', 'Novela satírica', 'Editorial: Debolsillo', 'George Orwell', 20, 'ACTIVE', NOW(), NOW()),
(159, 10, 'tenant_10', 'Guitarra Acústica Yamaha F310', 'Guitarra acústica de iniciación', 'Cuerdas de acero, color natural', 'Yamaha', 5, 'ACTIVE', NOW(), NOW()),
(160, 10, 'tenant_10', 'Teclado Yamaha PSR-E373', 'Teclado portátil con 61 teclas', '61 teclas, 622 sonidos', 'Yamaha', 5, 'ACTIVE', NOW(), NOW()),
(161, 1, 'tenant_1', 'Monitor LG 24"', 'Monitor Full HD para oficina', '24 pulgadas, resolución 1920x1080', 'LG', 5, 'ACTIVE', NOW(), NOW()),
(162, 1, 'tenant_1', 'Auriculares HyperX Cloud II', 'Auriculares gaming con micrófono', 'Confortable, sonido 7.1', 'HyperX', 10, 'ACTIVE', NOW(), NOW()),
(163, 2, 'tenant_2', 'Cámara Canon EOS 2000D', 'Cámara réflex digital', '24.1 MP, lente 18-55mm', 'Canon', 5, 'ACTIVE', NOW(), NOW()),
(164, 2, 'tenant_2', 'Cámara Nikon D3500', 'Cámara réflex para principiantes', '24.2 MP, lente 18-55mm', 'Nikon', 5, 'ACTIVE', NOW(), NOW()),
(165, 3, 'tenant_3', 'Refrigerador LG 350L', 'Refrigerador con congelador superior', '350L, eficiencia A+', 'LG', 3, 'ACTIVE', NOW(), NOW()),
(166, 3, 'tenant_3', 'Horno Microondas Whirlpool 28L', 'Microondas digital con grill', '28 litros, 900W', 'Whirlpool', 5, 'ACTIVE', NOW(), NOW()),
(167, 4, 'tenant_4', 'Balón Baloncesto Molten', 'Balón oficial FIBA', 'Tamaño 7, cosido a mano', 'Molten', 20, 'ACTIVE', NOW(), NOW()),
(168, 4, 'tenant_4', 'Raqueta Pádel Vision', 'Raqueta profesional', 'Peso 360g, grip 2', 'Vision', 5, 'ACTIVE', NOW(), NOW()),
(169, 5, 'tenant_5', 'Zapatillas Asics Gel', 'Zapatillas running', 'Talla 42, color azul', 'Asics', 15, 'ACTIVE', NOW(), NOW()),
(170, 5, 'tenant_5', 'Botas Caterpillar Colorado', 'Botas resistentes', 'Talla 43, color marrón', 'Caterpillar', 10, 'ACTIVE', NOW(), NOW()),
(171, 6, 'tenant_6', 'Queso Manchego 500g', 'Queso curado artesanal', 'Paquete 500g', 'La Quesera', 30, 'ACTIVE', NOW(), NOW()),
(172, 6, 'tenant_6', 'Mantequilla 250g', 'Mantequilla natural', 'Paquete 250g', 'Lácteos Real', 30, 'ACTIVE', NOW(), NOW()),
(173, 7, 'tenant_7', 'Champú Head & Shoulders 400ml', 'Champú anticaspa', '400ml, aroma fresco', 'Head & Shoulders', 25, 'ACTIVE', NOW(), NOW()),
(174, 7, 'tenant_7', 'Crema Nivea Men 100ml', 'Hidratante ligera para hombres', '100ml, textura ligera', 'Nivea', 20, 'ACTIVE', NOW(), NOW()),
(175, 8, 'tenant_8', 'Neumático Michelin 205/55R16', 'Neumático para automóvil', '205/55R16, alta durabilidad', 'Michelin', 50, 'ACTIVE', NOW(), NOW()),
(176, 8, 'tenant_8', 'Filtro Aceite Mann', 'Filtro de aceite para motor', 'Modelo universal', 'Mann', 50, 'ACTIVE', NOW(), NOW()),
(177, 9, 'tenant_9', 'Libro "El Principito"', 'Novela infantil clásica', 'Editorial: Salamandra', 'Antoine de Saint-Exupéry', 20, 'ACTIVE', NOW(), NOW()),
(178, 9, 'tenant_9', 'Libro "Don Quijote de la Mancha"', 'Clásico de la literatura española', 'Editorial: Espasa', 'Miguel de Cervantes', 20, 'ACTIVE', NOW(), NOW()),
(179, 10, 'tenant_10', 'Guitarra Eléctrica Epiphone Les Paul', 'Guitarra eléctrica profesional', 'Color negro, 22 trastes', 'Epiphone', 5, 'ACTIVE', NOW(), NOW()),
(180, 10, 'tenant_10', 'Batería Roland TD-1K', 'Batería electrónica básica', '5 pads, módulo TD-1K', 'Roland', 2, 'ACTIVE', NOW(), NOW()),
(181, 1, 'tenant_1', 'Router TP-Link AC750', 'Router inalámbrico de doble banda', 'Velocidad 750 Mbps', 'TP-Link', 15, 'ACTIVE', NOW(), NOW()),
(182, 1, 'tenant_1', 'Switch Cisco 8 Puertos', 'Switch para red doméstica', '8 puertos Gigabit', 'Cisco', 10, 'ACTIVE', NOW(), NOW()),
(183, 2, 'tenant_2', 'Auriculares Beats Studio 3', 'Auriculares inalámbricos premium', 'Cancelación activa de ruido', 'Beats', 10, 'ACTIVE', NOW(), NOW()),
(184, 2, 'tenant_2', 'Altavoz Bluetooth Sony SRS-XB33', 'Altavoz portátil resistente al agua', '20W, resistente al agua', 'Sony', 15, 'ACTIVE', NOW(), NOW()),
(185, 3, 'tenant_3', 'Microondas Panasonic 30L', 'Microondas digital con grill', '30L, 1000W', 'Panasonic', 5, 'ACTIVE', NOW(), NOW()),
(186, 3, 'tenant_3', 'Lavadora LG 9kg', 'Lavadora automática', '9kg, 1200 rpm', 'LG', 3, 'ACTIVE', NOW(), NOW()),
(187, 4, 'tenant_4', 'Pelota Voleibol Mikasa VQ2000', 'Balón oficial Voleibol', 'Tamaño 5, material sintético', 'Mikasa', 20, 'ACTIVE', NOW(), NOW()),
(188, 4, 'tenant_4', 'Raqueta Squash Tecnifibre', 'Raqueta profesional', 'Peso 150g', 'Tecnifibre', 5, 'ACTIVE', NOW(), NOW()),
(189, 5, 'tenant_5', 'Zapatillas Nike Air Max', 'Zapatillas deportivas clásicas', 'Talla 42, color negro', 'Nike', 15, 'ACTIVE', NOW(), NOW()),
(190, 5, 'tenant_5', 'Sandalias Birkenstock', 'Sandalias cómodas y ligeras', 'Talla 40, color marrón', 'Birkenstock', 20, 'ACTIVE', NOW(), NOW()),
(191, 6, 'tenant_6', 'Leche Entera 1L', 'Leche fresca natural', '1 litro, envase carton', 'Lala', 50, 'ACTIVE', NOW(), NOW()),
(192, 6, 'tenant_6', 'Yogur Fresa 1kg', 'Yogur natural con sabor a fresa', '1 kg, sabor fresa', 'Danone', 30, 'ACTIVE', NOW(), NOW()),
(193, 7, 'tenant_7', 'Gel Dentífrico Sensodyne 100ml', 'Pasta dental para dientes sensibles', '100ml, sabor menta', 'Sensodyne', 30, 'ACTIVE', NOW(), NOW()),
(194, 7, 'tenant_7', 'Enjuague Bucal Oral-B 500ml', 'Enjuague antibacteriano', '500ml, sabor mentol', 'Oral-B', 25, 'ACTIVE', NOW(), NOW()),
(195, 8, 'tenant_8', 'Pastillas Freno Ferodo', 'Pastillas de freno delanteras', 'Modelo universal', 'Ferodo', 50, 'ACTIVE', NOW(), NOW()),
(196, 8, 'tenant_8', 'Aceite Motor Valvoline 5W40', 'Aceite sintético motor', '4 litros, motor gasolina', 'Valvoline', 40, 'ACTIVE', NOW(), NOW()),
(197, 9, 'tenant_9', 'Libro "Cien Años de Soledad"', 'Novela clásica latinoamericana', 'Editorial: Sudamericana', 'Gabriel García Márquez', 20, 'ACTIVE', NOW(), NOW()),
(198, 9, 'tenant_9', 'Libro "La Sombra del Viento"', 'Novela de misterio y literatura española', 'Editorial: Planeta', 'Carlos Ruiz Zafón', 20, 'ACTIVE', NOW(), NOW()),
(199, 10, 'tenant_10', 'Guitarra Acústica Cort AD810', 'Guitarra acústica profesional', 'Cuerdas de acero, color natural', 'Cort', 5, 'ACTIVE', NOW(), NOW()),
(200, 10, 'tenant_10', 'Teclado Roland GO:KEYS 61', 'Teclado portátil con 61 teclas', '61 teclas, 500 sonidos', 'Roland', 5, 'ACTIVE', NOW(), NOW());

-- =====================================
-- PRODUCTOS 201-250
-- =====================================
INSERT INTO dbo.product (id, category_id, tenant_id, name, description, technical_details, brand, min_stock, status, created_at, updated_at)
VALUES
(201, 1, 'tenant_1', 'Laptop HP Pavilion 15', 'Laptop de 15 pulgadas con buena autonomía', 'Intel i5, 8GB RAM, 512GB SSD', 'HP', 5, 'ACTIVE', NOW(), NOW()),
(202, 1, 'tenant_1', 'Laptop Lenovo ThinkPad E14', 'Laptop robusta para oficina', 'Intel i7, 16GB RAM, 256GB SSD', 'Lenovo', 5, 'ACTIVE', NOW(), NOW()),
(203, 2, 'tenant_2', 'Smartphone Samsung Galaxy S22', 'Teléfono inteligente gama alta', '256GB almacenamiento, 8GB RAM', 'Samsung', 10, 'ACTIVE', NOW(), NOW()),
(204, 2, 'tenant_2', 'Smartphone Xiaomi Redmi Note 12', 'Teléfono económico con buena cámara', '128GB almacenamiento, 6GB RAM', 'Xiaomi', 10, 'ACTIVE', NOW(), NOW()),
(205, 3, 'tenant_3', 'Smart TV LG 55" OLED', 'Televisor OLED con colores vivos', '55 pulgadas, 4K UHD, webOS', 'LG', 3, 'ACTIVE', NOW(), NOW()),
(206, 3, 'tenant_3', 'Smart TV Samsung 50" QLED', 'Televisor QLED con alta calidad', '50 pulgadas, 4K UHD, Tizen OS', 'Samsung', 3, 'ACTIVE', NOW(), NOW()),
(207, 4, 'tenant_4', 'Bicicleta MTB Giant 27.5"', 'Bicicleta de montaña para todo terreno', '27.5 pulgadas, 21 velocidades', 'Giant', 2, 'ACTIVE', NOW(), NOW()),
(208, 4, 'tenant_4', 'Bicicleta Ruta Cannondale', 'Bicicleta ligera de carretera', 'Carbono, 22 velocidades', 'Cannondale', 2, 'ACTIVE', NOW(), NOW()),
(209, 5, 'tenant_5', 'Tenis Nike Revolution 6', 'Tenis deportivos para running', 'Talla 42, color gris', 'Nike', 10, 'ACTIVE', NOW(), NOW()),
(210, 5, 'tenant_5', 'Tenis Adidas Ultraboost', 'Tenis running de alto rendimiento', 'Talla 43, color negro', 'Adidas', 10, 'ACTIVE', NOW(), NOW()),
(211, 6, 'tenant_6', 'Aceite de Oliva Extra Virgen 1L', 'Aceite de oliva premium', 'Botella 1L', 'Carbonell', 20, 'ACTIVE', NOW(), NOW()),
(212, 6, 'tenant_6', 'Café Molido Illy 250g', 'Café premium molido', '250g, tueste medio', 'Illy', 30, 'ACTIVE', NOW(), NOW()),
(213, 7, 'tenant_7', 'Perfume Chanel Bleu 100ml', 'Perfume masculino elegante', '100ml, notas amaderadas', 'Chanel', 15, 'ACTIVE', NOW(), NOW()),
(214, 7, 'tenant_7', 'Loción Corporal Nivea 200ml', 'Hidratante para piel seca', '200ml, aroma neutro', 'Nivea', 25, 'ACTIVE', NOW(), NOW()),
(215, 8, 'tenant_8', 'Neumático Bridgestone 205/55R16', 'Neumático de alta durabilidad', '205/55R16', 'Bridgestone', 50, 'ACTIVE', NOW(), NOW()),
(216, 8, 'tenant_8', 'Aceite Motor Total Quartz 5W40 4L', 'Aceite sintético para motor', '4 litros, motor gasolina', 'Total', 40, 'ACTIVE', NOW(), NOW()),
(217, 9, 'tenant_9', 'Libro "El Código Da Vinci"', 'Novela de misterio y suspenso', 'Editorial: Planeta', 'Dan Brown', 15, 'ACTIVE', NOW(), NOW()),
(218, 9, 'tenant_9', 'Libro "Ángeles y Demonios"', 'Novela de misterio y conspiración', 'Editorial: Planeta', 'Dan Brown', 15, 'ACTIVE', NOW(), NOW()),
(219, 10, 'tenant_10', 'Guitarra Acústica Takamine', 'Guitarra acústica profesional', 'Cuerdas de acero, color natural', 'Takamine', 5, 'ACTIVE', NOW(), NOW()),
(220, 10, 'tenant_10', 'Teclado Yamaha PSR-E463', 'Teclado portátil con 61 teclas', '61 teclas, 758 sonidos', 'Yamaha', 5, 'ACTIVE', NOW(), NOW()),
(221, 1, 'tenant_1', 'Auriculares Sony WH-CH710N', 'Auriculares inalámbricos con cancelación de ruido', 'Bluetooth, 35 horas batería', 'Sony', 10, 'ACTIVE', NOW(), NOW()),
(222, 1, 'tenant_1', 'Monitor Dell 27" Ultrasharp', 'Monitor IPS para diseño y productividad', '27 pulgadas, resolución 2560x1440', 'Dell', 5, 'ACTIVE', NOW(), NOW()),
(223, 2, 'tenant_2', 'Camisa Ralph Lauren', 'Camisa casual elegante', 'Talla M, color blanco', 'Ralph Lauren', 10, 'ACTIVE', NOW(), NOW()),
(224, 2, 'tenant_2', 'Chaqueta North Face', 'Chaqueta outdoor resistente', 'Talla L, color negro', 'North Face', 5, 'ACTIVE', NOW(), NOW()),
(225, 3, 'tenant_3', 'Refrigerador Mabe 350L', 'Refrigerador con congelador superior', '350L, eficiencia A+', 'Mabe', 3, 'ACTIVE', NOW(), NOW()),
(226, 3, 'tenant_3', 'Horno Microondas LG 32L', 'Microondas digital con grill', '32L, 1000W', 'LG', 5, 'ACTIVE', NOW(), NOW()),
(227, 4, 'tenant_4', 'Balón Fútbol Adidas Tango', 'Balón oficial tamaño 5', 'Material sintético, cosido a mano', 'Adidas', 20, 'ACTIVE', NOW(), NOW()),
(228, 4, 'tenant_4', 'Raqueta Tenis Wilson Pro Staff', 'Raqueta profesional', 'Peso 300g, grip 4 3/8', 'Wilson', 5, 'ACTIVE', NOW(), NOW()),
(229, 5, 'tenant_5', 'Zapatillas Puma RS-Fast', 'Zapatillas deportivas', 'Talla 42, color negro', 'Puma', 15, 'ACTIVE', NOW(), NOW()),
(230, 5, 'tenant_5', 'Sandalias Crocs Classic', 'Sandalias cómodas para diario', 'Talla 40, color azul', 'Crocs', 10, 'ACTIVE', NOW(), NOW()),
(231, 6, 'tenant_6', 'Leche Deslactosada 1L', 'Leche fresca sin lactosa', '1 litro, envase carton', 'Lala', 50, 'ACTIVE', NOW(), NOW()),
(232, 6, 'tenant_6', 'Yogur Natural Fage 1kg', 'Yogur griego natural', '1 kg, sabor natural', 'Fage', 30, 'ACTIVE', NOW(), NOW()),
(233, 7, 'tenant_7', 'Champú Pantene 400ml', 'Champú nutritivo', '400ml, aroma floral', 'Pantene', 25, 'ACTIVE', NOW(), NOW()),
(234, 7, 'tenant_7', 'Crema Facial Garnier 50ml', 'Hidratante ligera para rostro', '50ml, textura ligera', 'Garnier', 20, 'ACTIVE', NOW(), NOW()),
(235, 8, 'tenant_8', 'Batería Bosch 12V 60Ah', 'Batería de automóvil', '12V, 60Ah, libre de mantenimiento', 'Bosch', 20, 'ACTIVE', NOW(), NOW()),
(236, 8, 'tenant_8', 'Filtro Aire K&N', 'Filtro de alto flujo para motor', 'Modelo universal', 'K&N', 50, 'ACTIVE', NOW(), NOW()),
(237, 9, 'tenant_9', 'Libro "El Alquimista"', 'Novela filosófica', 'Editorial: Planeta', 'Paulo Coelho', 20, 'ACTIVE', NOW(), NOW()),
(238, 9, 'tenant_9', 'Libro "Siddhartha"', 'Novela filosófica oriental', 'Editorial: Anaya', 'Hermann Hesse', 20, 'ACTIVE', NOW(), NOW()),
(239, 10, 'tenant_10', 'Bajo Eléctrico Ibanez GSR200', 'Bajo eléctrico de 4 cuerdas', 'Color negro, maple neck', 'Ibanez', 5, 'ACTIVE', NOW(), NOW()),
(240, 10, 'tenant_10', 'Batería Electrónica Alesis Nitro', 'Kit de batería electrónica completo', '8 pads, módulo Nitro', 'Alesis', 2, 'ACTIVE', NOW(), NOW()),
(241, 1, 'tenant_1', 'Router Linksys AC1200', 'Router inalámbrico de doble banda', 'Velocidad 1200 Mbps', 'Linksys', 15, 'ACTIVE', NOW(), NOW()),
(242, 1, 'tenant_1', 'Switch TP-Link 16 Puertos', 'Switch para red doméstica', '16 puertos Gigabit', 'TP-Link', 10, 'ACTIVE', NOW(), NOW()),
(243, 2, 'tenant_2', 'Auriculares Bose QuietComfort 35', 'Auriculares inalámbricos premium', 'Cancelación activa de ruido', 'Bose', 10, 'ACTIVE', NOW(), NOW()),
(244, 2, 'tenant_2', 'Altavoz Bluetooth JBL Charge 5', 'Altavoz portátil resistente al agua', '30W, resistente al agua', 'JBL', 15, 'ACTIVE', NOW(), NOW()),
(245, 3, 'tenant_3', 'Microondas Samsung 32L', 'Microondas digital con grill', '32L, 1000W', 'Samsung', 5, 'ACTIVE', NOW(), NOW()),
(246, 3, 'tenant_3', 'Lavadora Mabe 10kg', 'Lavadora automática', '10kg, 1200 rpm', 'Mabe', 3, 'ACTIVE', NOW(), NOW()),
(247, 4, 'tenant_4', 'Pelota Baloncesto Spalding', 'Balón oficial NBA', 'Tamaño 7, material sintético', 'Spalding', 20, 'ACTIVE', NOW(), NOW()),
(248, 4, 'tenant_4', 'Raqueta Pádel Head', 'Raqueta profesional', 'Peso 360g, grip 2', 'Head', 5, 'ACTIVE', NOW(), NOW()),
(249, 5, 'tenant_5', 'Zapatillas New Balance 574', 'Zapatillas clásicas', 'Talla 42, color gris', 'New Balance', 15, 'ACTIVE', NOW(), NOW()),
(250, 5, 'tenant_5', 'Botas Timberland', 'Botas resistentes', 'Talla 43, color marrón', 'Timberland', 10, 'ACTIVE', NOW(), NOW());

INSERT INTO dbo.product_variant (product_id, product_code, description, price, attributes, created_at, updated_at)
VALUES
(1, 'HP-PAV-15-001', 'Laptop HP Pavilion 15, color gris', 750.00, '{"color": "gris", "ram": "8GB", "storage": "512GB SSD"}', NOW(), NOW()),
(2, 'LEN-E14-001', 'Laptop Lenovo ThinkPad E14, color negro', 950.00, '{"color": "negro", "ram": "16GB", "storage": "256GB SSD"}', NOW(), NOW()),
(3, 'SAM-S22-256', 'Smartphone Samsung Galaxy S22, 256GB', 850.00, '{"color": "negro", "storage": "256GB", "ram": "8GB"}', NOW(), NOW()),
(4, 'XIA-RED12-128', 'Smartphone Xiaomi Redmi Note 12, 128GB', 250.00, '{"color": "azul", "storage": "128GB", "ram": "6GB"}', NOW(), NOW()),
(5, 'LG-OLED-55', 'Smart TV LG 55 OLED', 1200.00, '{"size": "55in", "type": "OLED", "resolution": "4K"}', NOW(), NOW()),
(6, 'SAM-QLED-50', 'Smart TV Samsung 50 QLED', 1000.00, '{"size": "50in", "type": "QLED", "resolution": "4K"}', NOW(), NOW()),
(7, 'GIANT-MTB-275', 'Bicicleta MTB Giant 27.5', 600.00, '{"size": "27.5in", "gears": 21, "type": "MTB"}', NOW(), NOW()),
(8, 'CAN-RUTA-CARB', 'Bicicleta Ruta Cannondale Carbono', 900.00, '{"type": "Ruta", "material": "Carbono", "gears": 22}', NOW(), NOW()),
(9, 'NIKE-R6-42', 'Tenis Nike Revolution 6, talla 42', 80.00, '{"size": 42, "color": "gris"}', NOW(), NOW()),
(10, 'ADID-UB-43', 'Tenis Adidas Ultraboost, talla 43', 120.00, '{"size": 43, "color": "negro"}', NOW(), NOW()),
(11, 'CARB-OLIVA-1L', 'Aceite de Oliva Extra Virgen 1L', 15.00, '{"volume": "1L"}', NOW(), NOW()),
(12, 'ILLY-250G', 'Café Molido Illy 250g', 12.00, '{"weight": "250g"}', NOW(), NOW()),
(13, 'CH-BLEU-100', 'Perfume Chanel Bleu 100ml', 110.00, '{"volume": "100ml"}', NOW(), NOW()),
(14, 'NIVEA-LO-200', 'Loción Corporal Nivea 200ml', 8.00, '{"volume": "200ml"}', NOW(), NOW()),
(15, 'BRID-205-55R16', 'Neumático Bridgestone 205/55R16', 120.00, '{"size": "205/55R16"}', NOW(), NOW()),
(16, 'TOTAL-Q5W40-4L', 'Aceite Motor Total Quartz 5W40 4L', 35.00, '{"volume": "4L"}', NOW(), NOW()),
(17, 'DAVINCI-001', 'Libro "El Código Da Vinci"', 20.00, '{"language": "Español"}', NOW(), NOW()),
(18, 'ANG-DEMON-001', 'Libro "Ángeles y Demonios"', 18.00, '{"language": "Español"}', NOW(), NOW()),
(19, 'TAK-ACOUSTIC', 'Guitarra Acústica Takamine', 500.00, '{"color": "natural", "strings": "steel"}', NOW(), NOW()),
(20, 'YAM-PSR-E463', 'Teclado Yamaha PSR-E463', 350.00, '{"keys": 61, "sounds": 758}', NOW(), NOW());

INSERT INTO dbo.product_variant (product_id, product_code, description, price, attributes, created_at, updated_at)
VALUES
(51, 'HP-ENVY-13', 'Laptop HP Envy 13, color plata', 850.00, '{"color": "plata", "ram": "16GB", "storage": "512GB SSD"}', NOW(), NOW()),
(52, 'LEN-YOGA-7', 'Laptop Lenovo Yoga 7, color gris', 950.00, '{"color": "gris", "ram": "16GB", "storage": "512GB SSD"}', NOW(), NOW()),
(53, 'SAM-GA-S21', 'Smartphone Samsung Galaxy S21, 128GB', 700.00, '{"color": "negro", "storage": "128GB", "ram": "8GB"}', NOW(), NOW()),
(54, 'XIA-RED11-64', 'Smartphone Xiaomi Redmi Note 11, 64GB', 180.00, '{"color": "blanco", "storage": "64GB", "ram": "4GB"}', NOW(), NOW()),
(55, 'LG-OLED-65', 'Smart TV LG 65 OLED', 1500.00, '{"size": "65in", "type": "OLED", "resolution": "4K"}', NOW(), NOW()),
(56, 'SAM-QLED-55', 'Smart TV Samsung 55 QLED', 1200.00, '{"size": "55in", "type": "QLED", "resolution": "4K"}', NOW(), NOW()),
(57, 'GIANT-MTB-29', 'Bicicleta MTB Giant 29', 650.00, '{"size": "29in", "gears": 21, "type": "MTB"}', NOW(), NOW()),
(58, 'CAN-ROAD-CA', 'Bicicleta Ruta Cannondale Carbono', 950.00, '{"type": "Ruta", "material": "Carbono", "gears": 22}', NOW(), NOW()),
(59, 'NIKE-ZOOM-42', 'Tenis Nike Zoom, talla 42', 110.00, '{"size": 42, "color": "negro"}', NOW(), NOW()),
(60, 'ADID-UBOOST-44', 'Tenis Adidas Ultraboost, talla 44', 130.00, '{"size": 44, "color": "blanco"}', NOW(), NOW()),
(61, 'CARB-OLIVA-2L', 'Aceite de Oliva Extra Virgen 2L', 25.00, '{"volume": "2L"}', NOW(), NOW()),
(62, 'ILLY-500G', 'Café Molido Illy 500g', 20.00, '{"weight": "500g"}', NOW(), NOW()),
(63, 'CH-COCO-100', 'Perfume Coco Chanel 100ml', 120.00, '{"volume": "100ml"}', NOW(), NOW()),
(64, 'NIVEA-LO-400', 'Loción Corporal Nivea 400ml', 15.00, '{"volume": "400ml"}', NOW(), NOW()),
(65, 'BRID-195-50R15', 'Neumático Bridgestone 195/50R15', 110.00, '{"size": "195/50R15"}', NOW(), NOW()),
(66, 'TOTAL-Q5W30-4L', 'Aceite Motor Total Quartz 5W30 4L', 33.00, '{"volume": "4L"}', NOW(), NOW()),
(67, 'DA-VINCI-002', 'Libro "Inferno"', 22.00, '{"language": "Español"}', NOW(), NOW()),
(68, 'ANG-DEMON-002', 'Libro "El Código Da Vinci"', 20.00, '{"language": "Español"}', NOW(), NOW()),
(69, 'TAK-ACOUSTIC-2', 'Guitarra Acústica Takamine, color natural', 520.00, '{"color": "natural", "strings": "steel"}', NOW(), NOW()),
(70, 'YAM-PSR-E463-2', 'Teclado Yamaha PSR-E463', 360.00, '{"keys": 61, "sounds": 758}', NOW(), NOW());

