spring:
  config:
    import: classpath:application.yml
  datasource:
    url: jdbc:postgresql://${MEDIA_DB_HOST}:${MEDIA_DB_PORT}/${MEDIA_DB_NAME}
    username: ${MEDIA_DB_USER}
    password: ${MEDIA_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      default_schema: dbo
      show-sql: true

media:
  storage:
    provider: cloudinary

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

server:
 port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/