spring:
  application:
    name: gateway-service

  cloud:
    
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order/**
              filters:
                - StripPrefix=1
            - id: tenant-service
              uri: lb://TENANT-SERVICE
              predicates:
                - Path=/tenant/**
              filters:
                - StripPrefix=1
            - id: media-service
              uri: lb://MEDIA-SERVICE
              predicates:
                - Path=/media/**
              filters:
                - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    fetch-registry: true
    register-with-eureka: true
    prefer-ip-address: true
    ip-address: 127.0.0.1